apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-htmlcssjs-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-htmlcssjs-app
  template:
    metadata:
      labels:
        app: my-htmlcssjs-app
    spec:
      containers:
      - name: my-htmlcssjs-app
        image: pramoddhote/htmlcssjs:latest
        ports:
        - containerPort: 80
