name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Get short commit SHA
      - name: Get short SHA
        id: vars
        run: echo "::set-output name=short_sha::$(echo ${{ github.sha }} | cut -c1-7)"

      # Log in to GitHub Container Registry using PAT
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT_GITHUB }}  # Use your Personal Access Token stored as GHCR_PAT

      # Build and push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.actor }}/htmlcssjs/myimage:${{ steps.vars.outputs.short_sha }}

      # Post build cleanup - Docker image prune
      - name: Post build cleanup
        run: docker image prune -f

      # Clean up old images, keeping only the latest 3
      - name: Delete old versions
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }}
        run: |
          gh api /users/${{ github.actor }}/packages/container/${{ github.repository }}%2Fmyimage/versions \
            --jq '.[] | .id' | tail -n +4 | xargs -I {} gh api /users/${{ github.actor }}/packages/container/${{ github.repository }}%2Fmyimage/versions/{} -X DELETE \
            -H "Authorization: Bearer ${GITHUB_TOKEN}"

            
