name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Get short SHA
        id: vars
        run: echo "::set-output name=short_sha::$(echo ${{ github.sha }} | cut -c1-7)"

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT_GITHUB }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/myimage:${{ steps.vars.outputs.short_sha }}

      - name: Clean up old images from GHCR
        run: |
          curl -s -H "Authorization: Bearer ${{ secrets.PAT_GITHUB }}" \
          https://api.github.com/orgs/${{ github.repository_owner }}/packages/container/myimage/versions \
          | jq '.[] | select(.tags | index("latest") | not) | .id' \
          | xargs -I {} curl -X DELETE \
          -H "Authorization: Bearer ${{ secrets.PAT_GITHUB }}" \
          https://api.github.com/orgs/${{ github.repository_owner }}/packages/container/myimage/versions/{}

      - name: Post build cleanup
        run: docker image prune -f
